"""
Recria tabelas e insere todas as receitas.
Execute: python setup_banco.py
"""
import psycopg2, os

DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    raise ValueError("DATABASE_URL nao configurada.")

conn = psycopg2.connect(DATABASE_URL)
cur = conn.cursor()

cur.execute("DROP TABLE IF EXISTS historico CASCADE;")
cur.execute("DROP TABLE IF EXISTS ultima_receita CASCADE;")
cur.execute("DROP TABLE IF EXISTS cache CASCADE;")
cur.execute("DROP TABLE IF EXISTS receitas CASCADE;")

cur.execute("""
CREATE TABLE receitas (
    id SERIAL PRIMARY KEY,
    nome TEXT NOT NULL,
    keywords TEXT[] NOT NULL,
    categoria TEXT NOT NULL,
    ingredientes TEXT,
    modo TEXT
);""")
cur.execute("""
CREATE TABLE cache (
    chave TEXT PRIMARY KEY,
    resposta TEXT NOT NULL,
    criado_em TIMESTAMP DEFAULT NOW()
);""")
cur.execute("""
CREATE TABLE ultima_receita (
    session_id TEXT PRIMARY KEY,
    receita_id INTEGER REFERENCES receitas(id),
    atualizado_em TIMESTAMP DEFAULT NOW()
);""")
cur.execute("""
CREATE TABLE historico (
    id SERIAL PRIMARY KEY,
    session_id TEXT NOT NULL,
    mensagem TEXT NOT NULL,
    resposta TEXT NOT NULL,
    criado_em TIMESTAMP DEFAULT NOW()
);""")
conn.commit()
print("Tabelas criadas.")

RECEITAS = [
    {"nome":"Sorvete Artesanal","keywords":["sorvete"],"categoria":"quente","ingredientes":"1 litro de leite\n1 xicara de creme de leite\n1 e 1/2 xicara de acucar refinado\n1 xicara de leite em po\n1 colher (sopa) rasa de liga neutra\n1 colher (sopa) de po sabor para sorvete\n1 colher (sopa) de emulsificante","modo":"1. Bater o leite, o creme de leite, o acucar, o leite em po e a liga neutra por 3 minutos no liquidificador.\n2. Colocar a mistura em vasilhas de aluminio para gelar.\n3. Depois de gelada, a mistura vira um bloco (massa basica do sorvete).\n4. Colocar a massa em pedacos na batedeira, juntar o sabor de sua preferencia e o emulsificante. Bater em velocidade maxima por 5 minutos.\n5. Colocar em potes fechados e levar ao freezer."},
    {"nome":"Mousse de Cafe com Chocolate","keywords":["mousse","cafe"],"categoria":"quente","ingredientes":"250ml de leite de coco\n12g de gelatina sem sabor\n100ml de cafe\n2 colheres (sopa) de adocante\nEssencia de baunilha a gosto\nCobertura:\n150ml de leite de coco\n50ml de cafe\n2 colheres (sopa) de adocante\n1 colher (sopa) de cacau sem acucar","modo":"1. Hidratar a gelatina no cafe, mexer ate dissolver bem (reserve).\n2. No liquidificador acrescente o leite de coco, essencia de baunilha, o adocante e por ultimo a gelatina dissolvida no cafe. Bater por 1 minuto.\n3. Despeje em um refratario e leve a geladeira por 2 horas.\n4. Para a cobertura: misture todos os ingredientes e leve ao micro-ondas de 30 em 30 segundos ate formar uma calda. Deixe esfriar.\n5. Espalhe a cobertura sobre a mousse gelada e leve a geladeira por mais 30 minutos."},
    {"nome":"Mousse de Morango sem Leite Condensado","keywords":["morango"],"categoria":"quente","ingredientes":"1 caixinha de morangos picados\n1 caixinha de creme de leite\n2 potes de iogurte natural","modo":"1. Bata no liquidificador todos os ingredientes.\n2. Despeje em tacas individuais.\n3. Leve a geladeira por 3 horas.\n4. Decore com pedacos de morango na hora de servir."},
    {"nome":"Bombom de Prestigio","keywords":["prestigio"],"categoria":"quente","ingredientes":"1/2 lata de leite condensado (200g)\n2 pacotes de coco ralado (200g)\n200g de chocolate ao leite ou meio amargo","modo":"1. Misture bem o coco ralado com o leite condensado.\n2. Faca bolinhas e disponha em uma forma.\n3. Leve a geladeira por 30 minutos.\n4. Derreta o chocolate e banhe os bombons.\n5. Coloque sobre papel manteiga e deixe secar."},
    {"nome":"Bombom Surpresa com Pacoca","keywords":["pacoca","surpresa"],"categoria":"quente","ingredientes":"200g de bolacha maisena moida\n1 xicara de pacoca picada (aprox. 7 pacocas)\n1 lata de leite condensado\nUvas verdes sem sementes\n300g de chocolate meio amargo fracionado","modo":"1. Misture a bolacha moida com a pacoca e va acrescentando o leite condensado aos poucos ate chegar ao ponto de brigadeiro.\n2. Umedeca a palma da mao com agua, pegue um pouco da mistura e faca bolinhas.\n3. Aperte cada bolinha na palma da mao, coloque uma uva no meio e feche.\n4. Derreta o chocolate fracionado e banhe as bolinhas.\n5. Coloque sobre papel manteiga e deixe secar."},
    {"nome":"Bicho de Pe","keywords":["bicho de pe"],"categoria":"quente","ingredientes":"1 lata de leite condensado\n1 pacote de gelatina de morango\n1 colher (sopa) de manteiga ou margarina sem sal\nAcucar cristal para passar","modo":"1. Em uma panela de fundo grosso, misture o leite condensado, a manteiga e a gelatina.\n2. Leve ao fogo baixo mexendo sem parar ate desgrudar do fundo (ponto de brigadeiro).\n3. Despeje em um recipiente, cubra com plastico filme e leve a geladeira para esfriar.\n4. Apos esfriar, passe um pouco de oleo nas maos e enrole os docinhos.\n5. Passe no acucar cristal e sirva."},
    {"nome":"Pacoquinha de Leite Condensado","keywords":["pacoquinha","amendoim"],"categoria":"quente","ingredientes":"250g de amendoim torrado e moido\n1/2 pacote de bolacha maisena moida (100g aprox.)\n1/2 lata de leite condensado","modo":"1. Misture com a mao amassando bem todos os ingredientes ate virar uma massa compacta.\n2. Distribua a massa em uma assadeira untada, apertando bem.\n3. Leve a geladeira por 30 minutos.\n4. Apos endurecer, corte no tamanho desejado."},
    {"nome":"Pizza de Chocolate Brigadeiro","keywords":["pizza"],"categoria":"quente","ingredientes":"1 disco de pizza medio (assado)\n1 lata de leite condensado\n1 colher (sopa) de cacau em po\n1 colher (sobremesa) de chocolate em po\nGranulado, cerejas em calda e folhas de hortela a gosto","modo":"1. Misture o leite condensado, o cacau e o chocolate em po numa panela.\n2. Leve ao fogo mexendo ate comecar a desgrudar do fundo (ponto de brigadeiro).\n3. Espalhe o brigadeiro sobre a massa ja assada.\n4. Finalize com granulado, cerejas e folhas de hortela."},
    {"nome":"Petit Gateau de Bacuri","keywords":["petit","gateau","bacuri"],"categoria":"quente","ingredientes":"200g de chocolate branco\n250g de manteiga\n5 gemas\n5 ovos inteiros\n350g de polpa de bacuri\n40g de acucar refinado","modo":"1. Derreta a manteiga e o chocolate branco em banho-maria.\n2. Retire do fogo e acrescente os ovos, as gemas e o acucar, mexendo com fouet.\n3. Ainda morno, acrescente a polpa de bacuri e misture.\n4. Unte as forminhas com manteiga e chocolate em po.\n5. Pre-aqueca o forno a 180 graus C e asse de 6 a 10 minutos (o centro deve ficar cremoso)."},
    {"nome":"Sequilhos de Limao","keywords":["sequilho","limao"],"categoria":"quente","ingredientes":"250g de amido de milho\n80g de acucar\n50g de manteiga\nRaspas e suco de 1 limao","modo":"1. Em um recipiente, acrescente o amido, o acucar, a manteiga e as raspas de limao. Misture ate formar uma farofa.\n2. Adicione o suco de limao aos poucos ate dar ponto para enrolar.\n3. Faca rolinhos e corte os sequilhos no tamanho desejado.\n4. Coloque em assadeira e leve a geladeira por 5 a 10 minutos.\n5. Leve ao forno pre-aquecido a 160 graus C de 15 a 18 minutos."},
    {"nome":"Brigadeiro Gourmet","keywords":["brigadeiro"],"categoria":"quente","ingredientes":"1 lata de leite condensado\n1 colher (sopa) de manteiga sem sal\n3 colheres (sopa) de cacau em po 100%\nGranulado belga para decorar","modo":"1. Em uma panela, misture o leite condensado, a manteiga e o cacau.\n2. Leve ao fogo medio, mexendo sempre, ate desgrudar do fundo.\n3. Despeje em prato untado com manteiga e deixe esfriar.\n4. Enrole com as maos untadas e passe no granulado."},
    {"nome":"Pave de Limao","keywords":["pave"],"categoria":"quente","ingredientes":"1 lata de leite condensado\n1 caixa de creme de leite\nSuco e raspas de 3 limoes\n1 pacote de biscoito maisena\nLeite para molhar o biscoito","modo":"1. Bata o leite condensado, o creme de leite, o suco e as raspas de limao.\n2. Molhe os biscoitos rapidamente no leite.\n3. Monte camadas alternando biscoito e creme em um refratario.\n4. Finalize com creme e raspas de limao.\n5. Leve a geladeira por no minimo 4 horas."},
    {"nome":"Torta de Limao Gelada","keywords":["torta de limao"],"categoria":"quente","ingredientes":"Base:\n200g de biscoito maisena triturado\n100g de manteiga derretida\nRecheio:\n1 lata de leite condensado\n1 caixa de creme de leite\nSuco de 4 limoes\nCobertura:\n1 caixa de creme de leite gelado\n2 colheres (sopa) de acucar","modo":"1. Misture o biscoito triturado com a manteiga. Forre o fundo de uma forma.\n2. Bata o leite condensado com o creme de leite e o suco de limao ate engrossar.\n3. Despeje sobre a base e leve a geladeira por 2 horas.\n4. Bata o creme de leite gelado com o acucar ate formar chantilly e cubra a torta."},
    {"nome":"Palha Italiana","keywords":["palha italiana"],"categoria":"quente","ingredientes":"1 lata de leite condensado\n1 colher (sopa) de manteiga\n2 colheres (sopa) de cacau em po\n1 pacote de biscoito maisena quebrado grosseiramente","modo":"1. Em uma panela, misture o leite condensado, a manteiga e o cacau.\n2. Leve ao fogo baixo mexendo ate comecar a desgrudar do fundo.\n3. Retire do fogo e misture o biscoito quebrado.\n4. Espalhe em uma forma forrada com papel manteiga.\n5. Deixe esfriar e corte em quadradinhos."},
    {"nome":"Cajuzinho","keywords":["cajuzinho"],"categoria":"quente","ingredientes":"200g de amendoim torrado e moido\n1 lata de leite condensado\n1 colher (sopa) de manteiga\nAcucar cristal amarelo para enrolar\nCravo para decorar","modo":"1. Misture o amendoim moido com o leite condensado e a manteiga numa panela.\n2. Leve ao fogo baixo mexendo ate desgrudar do fundo.\n3. Deixe esfriar e modele no formato de caju.\n4. Passe no acucar cristal e finalize com um cravo no topo."},
    {"nome":"Bolo Gelado de Chocolate","keywords":["bolo gelado"],"categoria":"quente","ingredientes":"Massa:\n3 ovos\n1 xicara de acucar\n1 xicara de farinha de trigo\n1/2 xicara de chocolate em po\n1 colher (sopa) de fermento\n1/2 xicara de leite\nCalda:\n1 lata de leite condensado\n1/2 xicara de chocolate em po\n1 caixinha de creme de leite","modo":"1. Bata os ovos com o acucar. Adicione os ingredientes secos alternando com o leite.\n2. Asse em forno a 180 graus C por 30 minutos.\n3. Para a calda: misture o leite condensado, o chocolate e o creme de leite numa panela. Leve ao fogo ate engrossar.\n4. Fure o bolo ainda quente com um garfo e despeje a calda por cima.\n5. Leve a geladeira por 2 horas antes de servir."},
    {"nome":"Geleia de Frutas Vermelhas","keywords":["geleia","frutas vermelhas"],"categoria":"quente","ingredientes":"500g de morangos\n200g de framboesas ou amoras\n300g de acucar\nSuco de 1 limao","modo":"1. Lave e pique as frutas.\n2. Misture com o acucar e o suco de limao numa panela.\n3. Leve ao fogo medio mexendo ocasionalmente ate engrossar (cerca de 30 minutos).\n4. Despeje em potes esterilizados ainda quente.\n5. Deixe esfriar e guarde na geladeira."},
    {"nome":"Picole de Maracuja","keywords":["picole","maracuja"],"categoria":"quente","ingredientes":"1 lata de leite condensado\n1 caixinha de creme de leite\n1 xicara de suco de maracuja concentrado","modo":"1. Bata todos os ingredientes no liquidificador por 2 minutos.\n2. Despeje nas forminhas de picole.\n3. Coloque os palitos e leve ao freezer por no minimo 6 horas."},
    {"nome":"Tortinha de Morango","keywords":["tortinha","tortinha de morango"],"categoria":"quente","ingredientes":"Base:\n100g de manteiga\n200g de farinha de trigo\n50g de acucar\n1 ovo\nRecheio:\n1 lata de leite condensado\n1 caixinha de creme de leite\n50ml de suco de limao\nMorangos frescos para decorar","modo":"1. Misture a manteiga, a farinha, o acucar e o ovo ate formar uma massa. Forre forminhas e asse a 180 graus C por 15 minutos.\n2. Bata o leite condensado, o creme de leite e o suco de limao ate engrossar.\n3. Recheie as tortinhas ja frias e decore com morangos."},
    {"nome":"Curau de Milho","keywords":["curau"],"categoria":"quente","ingredientes":"4 espigas de milho verde (ou 2 latas de milho)\n1 e 1/2 xicara de acucar\n500ml de leite\n1 colher (sopa) de manteiga\nCanela em po para polvilhar","modo":"1. Bata o milho com o leite no liquidificador e coe.\n2. Leve ao fogo com o acucar e a manteiga, mexendo sem parar.\n3. Cozinhe ate engrossar e soltar do fundo da panela.\n4. Despeje em formas ou tigelas.\n5. Polvilhe canela e sirva frio ou morno."},
    {"nome":"Cocada Mole","keywords":["cocada"],"categoria":"quente","ingredientes":"2 xicaras de coco ralado fresco ou seco\n2 xicaras de acucar\n1 xicara de agua\n1 colher (sopa) de manteiga","modo":"1. Dissolva o acucar na agua e leve ao fogo ate ponto de fio.\n2. Adicione o coco ralado e a manteiga.\n3. Mexa em fogo baixo ate engrossar e soltar do fundo.\n4. Despeje em forma untada com agua e deixe esfriar.\n5. Corte em pedacos e sirva."},
    {"nome":"Doce de Leite Caseiro","keywords":["doce de leite caseiro"],"categoria":"quente","ingredientes":"1 litro de leite integral\n300g de acucar\n1 colher (cafe) de bicarbonato de sodio","modo":"1. Misture o leite com o acucar e o bicarbonato numa panela de fundo grosso.\n2. Leve ao fogo medio mexendo sempre ate comecar a ferver.\n3. Reduza o fogo e continue mexendo ate engrossar e ficar com cor de caramelo (cerca de 1 hora).\n4. Despeje em potes esterilizados e deixe esfriar."},
    {"nome":"Pe de Moleque","keywords":["pe de moleque"],"categoria":"quente","ingredientes":"500g de amendoim torrado sem pele\n2 xicaras de acucar\n1/2 xicara de agua\n1 colher (sopa) de manteiga","modo":"1. Leve o acucar e a agua ao fogo ate caramelizar.\n2. Adicione o amendoim e a manteiga, mexendo rapidamente.\n3. Despeje sobre uma superficie untada com oleo.\n4. Espalhe com espatula e deixe esfriar.\n5. Quebre em pedacos e sirva."},
    {"nome":"Gelado de Coco","keywords":["gelado de coco","gelado"],"categoria":"quente","ingredientes":"1 litro de leite de coco\n1 lata de leite condensado\n1 caixa de creme de leite\n1 pacote de coco ralado (100g)","modo":"1. Misture todos os ingredientes no liquidificador.\n2. Despeje em forminhas de picole ou pote.\n3. Leve ao freezer por no minimo 4 horas.\n4. Sirva gelado."},
    {"nome":"Bolo de Abacaxi com Doce de Leite","keywords":["abacaxi","doce de leite"],"categoria":"frio","ingredientes":"Massa:\n1 ovo inteiro\n1 xicara de acucar\n50g de manteiga sem sal\n1 copo de iogurte\n4 colheres (sopa) de coco ralado desidratado\n1 pitada de sal\n1 xicara de farinha de trigo\n1 colher (sopa) rasa de fermento em po\nMontagem:\n1 abacaxi pequeno cortado em cubos\n1 lata de doce de leite","modo":"1. Misture os cubos de abacaxi com o doce de leite e reserve.\n2. Bata o ovo com o acucar ate ficar uma mistura clara.\n3. Junte a manteiga e o iogurte. Acrescente o coco ralado, o sal e a mistura de ovos.\n4. Acrescente a farinha misturando delicadamente. Por ultimo, acrescente o fermento.\n5. Em uma assadeira, coloque uma camada de massa, o recheio de abacaxi e cubra com o restante da massa.\n6. Polvilhe coco ralado e leve ao forno pre-aquecido a 180 graus C por 30 minutos."},
    {"nome":"Bolo de Cenoura com Pudim de Chocolate","keywords":["cenoura"],"categoria":"frio","ingredientes":"Bolo:\n2 ovos\n1 cenoura media\n1/2 xicara de oleo\n1 xicara de acucar\n1 xicara de farinha de trigo\n1 e 1/2 colher (cha) de fermento\nPudim:\n1 xicara de acucar (para caramelizar)\n1 lata de leite condensado\nA mesma medida de leite\n3 ovos\n5 colheres de chocolate em po","modo":"1. Em uma forma para pudim, caramelize o acucar no fogo ate dourar.\n2. No liquidificador, bata todos os ingredientes do pudim e despeje na forma caramelizada.\n3. Bata no liquidificador a cenoura, os ovos e o oleo. Transfira para um recipiente e acrescente a farinha, o acucar e por ultimo o fermento.\n4. Despeje a mistura do bolo sobre o pudim.\n5. Leve ao forno pre-aquecido a 180 graus C por aproximadamente 1 hora."},
    {"nome":"Bolo de Couve","keywords":["couve"],"categoria":"frio","ingredientes":"3 folhas medias de couve lavadas e picadas\n3 ovos inteiros\n250g de acucar\n60ml de oleo\n250g de farinha de trigo\n1 colher (sopa) de fermento quimico\n200ml de suco de laranja","modo":"1. No liquidificador, bata a couve, os ovos, o acucar e o oleo.\n2. Transfira para uma travessa e acrescente a farinha, o fermento e aos poucos o suco de laranja.\n3. Despeje em forma untada.\n4. Leve ao forno pre-aquecido a 180 graus C de 35 a 40 minutos."},
    {"nome":"Bolo de Fuba","keywords":["fuba"],"categoria":"frio","ingredientes":"3 ovos\n2 xicaras de acucar\n2 xicaras de fuba\n1 xicara de farinha de trigo\n1 xicara de oleo\n1 xicara de leite\n1 colher (sopa) de fermento em po","modo":"1. Bata o acucar com os ovos ate formar um creme claro.\n2. Acrescente aos poucos os demais ingredientes, menos o fermento.\n3. Apos bater bem, acrescente o fermento e misture delicadamente.\n4. Unte uma assadeira com manteiga e acucar cristal.\n5. Leve ao forno pre-aquecido a 180 graus C por 40 minutos ou ate dourar."},
    {"nome":"Bolo de Mandioca Cremoso","keywords":["mandioca"],"categoria":"frio","ingredientes":"500g de mandioca crua ralada\n200ml de leite de coco\n1 colher (sopa) de manteiga\n2 ovos\n1/2 xicara de coco ralado seco\n1 xicara de acucar","modo":"1. Misture bem todos os ingredientes.\n2. Unte a forma com oleo e acucar.\n3. Leve ao forno pre-aquecido a 180 graus C por 40 a 50 minutos."},
    {"nome":"Bolo de Chocolate Peteleco","keywords":["peteleco","chocolate"],"categoria":"frio","ingredientes":"Massa:\n3 xicaras de farinha de trigo\n2 xicaras de acucar\n1 xicara de chocolate em po\n1 colher (cha) de fermento em po\n1 colher (cha) de bicarbonato de sodio\n1 xicara de oleo\n2 ovos\n2 xicaras de agua fervente\nCobertura:\n6 colheres (sopa) de acucar\n2 colheres (sopa) de chocolate em po\n1 colher (cha) de raspas de laranja\n1 colher (cha) de manteiga\n1/2 xicara de agua","modo":"1. Peneire a farinha, o acucar, o chocolate, o fermento e o bicarbonato.\n2. Junte o oleo, os ovos e a agua fervente, misturando bem.\n3. Despeje em assadeira retangular untada.\n4. Asse em forno medio-alto (200 graus C) por 25 minutos.\n5. Para a cobertura: misture todos os ingredientes e leve ao fogo baixo ate obter calda grossa.\n6. Espalhe sobre o bolo ainda quente."},
    {"nome":"Bolo de Macaxeira Caramelizado","keywords":["macaxeira"],"categoria":"frio","ingredientes":"1 kg de macaxeira ralada\n4 ovos\n2 xicaras de acucar\n1 xicara de leite\n1 vidro de leite de coco\n1 xicara de farinha de trigo\n1 colher (sopa) de fermento quimico\n1/2 colher (cha) de sal\n1 xicara de coco ralado","modo":"1. Coloque a macaxeira ralada em uma tigela.\n2. Bata no liquidificador os ovos, o acucar, o leite de coco, o sal e o leite.\n3. Despeje na tigela com a macaxeira. Misture bem e acrescente o coco ralado, a farinha e por ultimo o fermento.\n4. Coloque em forma caramelizada.\n5. Leve ao forno pre-aquecido a 220 graus C por 50 a 60 minutos."},
    {"nome":"Pastel de Forno com Creme de Galinha","keywords":["pastel","galinha","guarana"],"categoria":"frio","ingredientes":"Massa:\n1 lata de refrigerante guarana\n500g de farinha de trigo\n300g de manteiga amolecida\nSal a gosto\n1 gema de ovo para pincelar\nRecheio:\n500g de peito de frango cozido e desfiado\n1 cebola picada\n2 colheres (sopa) de azeite\n2 colheres (sopa) de farinha de trigo\n1 xicara de leite\nSal, pimenta e salsinha a gosto","modo":"1. Misture todos os ingredientes da massa e amasse ate desgrudar das maos. Deixe descansar 30 minutos.\n2. Refogue a cebola no azeite. Junte o frango e a farinha. Adicione o leite aos poucos ate engrossar. Acerte o tempero.\n3. Ligue o forno a 180 graus C. Abra a massa, corte discos, coloque o recheio e feche. Pincele com a gema.\n4. Leve ao forno a 200 graus C por 20 minutos ou ate dourar."},
    {"nome":"Pudim de Queijo","keywords":["pudim","pudim de queijo"],"categoria":"frio","ingredientes":"Calda:\n1 e 1/2 xicara de acucar cristal\n1/2 xicara de agua\nPudim:\n2 latas de leite condensado\n2 copos de iogurte natural\n5 ovos\n1/2 xicara de farinha de trigo\n200g de queijo coalho ralado\n1 colher (cafe) de fermento","modo":"1. Para a calda: misture o acucar e a agua e deixe ferver ate caramelizar. Caramelize a forma.\n2. Bata no liquidificador o iogurte, o leite condensado, os ovos e o queijo.\n3. Junte a farinha e o fermento e bata novamente.\n4. Coloque na forma caramelizada e leve ao forno em banho-maria por 40 minutos a 180 graus C."},
    {"nome":"Navete Francesa","keywords":["navete"],"categoria":"frio","ingredientes":"Massa:\n250g de margarina\n250g de farinha de trigo\n3 gemas\n30ml de agua\nRecheio:\n600g de presunto\n200g de queijo mussarela\n200g de ricota\n50g de uvas passas\n50g de azeitona\n200g de milho verde\n3 ovos\n20g de cheiro verde\n400g de creme de leite","modo":"1. Para o recheio: processe o presunto e o queijo. Misture com o restante dos ingredientes.\n2. Para a massa: junte a margarina, o trigo, as gemas e a agua. Amasse ate ficar macia.\n3. Coloque a massa nas forminhas, acrescente o recheio.\n4. Leve ao forno medio a 180 graus C por 20 a 30 minutos."},
    {"nome":"Pao de Mel","keywords":["pao de mel"],"categoria":"frio","ingredientes":"3 xicaras de farinha de trigo\n1 xicara de acucar\n1/2 xicara de chocolate em po\n1 colher (sobremesa) de bicarbonato\n1 colher (cafe) de cravo em po\n1 colher (cafe) de canela em po\n1 e 1/2 xicara de leite morno\n1/2 xicara de mel","modo":"1. Coloque todos os ingredientes secos peneirados em uma vasilha.\n2. Acrescente o mel e o leite morno. Misture com a mao.\n3. Unte as forminhas de pao de mel.\n4. Leve ao forno pre-aquecido a 200 graus C por 20 minutos. Deixe esfriar e desenforme.\n5. Recheie com brigadeiro, beijinho ou doce de leite.\n6. Derreta chocolate ao leite e banhe os paes de mel."},
    {"nome":"Joelho ou Enroladinho de Presunto e Queijo","keywords":["presunto","joelho"],"categoria":"frio","ingredientes":"500ml de agua morna\n150ml de oleo\n4 colheres (sopa) de acucar\n1 colher (sopa) de sal\n2 pacotes de fermento biologico seco (20g)\n1kg de farinha de trigo\n500g de presunto\n500g de mussarela\nMolho de tomate e oregano a gosto","modo":"1. Misture a agua morna, o oleo, acucar, sal e o fermento. Adicione a farinha aos poucos e sove por 10 minutos.\n2. Deixe descansar por 10 minutos.\n3. Abra a massa, recheie com presunto, molho e queijo, feche e corte.\n4. Passe gema e polvilhe oregano.\n5. Leve ao forno pre-aquecido a 220 graus C por 30 a 35 minutos."},
    {"nome":"Bolo de Banana com Canela","keywords":["banana","canela"],"categoria":"frio","ingredientes":"3 bananas maduras amassadas\n2 ovos\n1 xicara de acucar\n1/2 xicara de oleo\n2 xicaras de farinha de trigo\n1 colher (sopa) de fermento\n1 colher (cha) de canela em po","modo":"1. Bata os ovos com o acucar e o oleo.\n2. Adicione as bananas amassadas e misture.\n3. Junte a farinha, a canela e o fermento.\n4. Despeje em forma untada.\n5. Leve ao forno a 180 graus C por 35 minutos."},
    {"nome":"Caldo Verde","keywords":["caldo verde","caldo"],"categoria":"frio","ingredientes":"500g de batata\n1 maco de couve fatiada bem fina\n200g de linguica calabresa fatiada\n1 cebola picada\n3 dentes de alho\n2 litros de agua\nSal, pimenta e azeite a gosto","modo":"1. Cozinhe as batatas ate amolecer. Bata com a agua no liquidificador.\n2. Volte ao fogo e adicione a cebola e o alho refogados no azeite.\n3. Acrescente a linguica e deixe cozinhar por 10 minutos.\n4. Adicione a couve fatiada bem fina e cozinhe por mais 3 minutos.\n5. Acerte o sal e sirva quente."},
    {"nome":"Pao de Batata","keywords":["pao de batata"],"categoria":"frio","ingredientes":"500g de batata cozida e amassada\n500g de farinha de trigo\n1 envelope de fermento biologico seco\n2 ovos\n50g de manteiga\n1 colher (cha) de sal\n2 colheres (sopa) de acucar\n100ml de leite morno","modo":"1. Misture o fermento com o leite morno e o acucar. Deixe descansar 10 minutos.\n2. Adicione a batata amassada, os ovos, a manteiga e o sal.\n3. Va acrescentando a farinha ate formar uma massa lisa.\n4. Sove por 10 minutos e deixe descansar ate dobrar de volume.\n5. Modele os paes e deixe crescer por mais 30 minutos.\n6. Leve ao forno a 180 graus C por 25 minutos."},
    {"nome":"Rosca Doce","keywords":["rosca"],"categoria":"frio","ingredientes":"500g de farinha de trigo\n100g de acucar\n1 envelope de fermento biologico seco\n3 ovos\n100g de manteiga\n100ml de leite morno\n1 colher (cha) de sal\nCobertura: 1 gema + 2 colheres de leite + acucar cristal","modo":"1. Misture o fermento com o leite morno e o acucar. Deixe ativar por 10 minutos.\n2. Adicione os ovos, a manteiga e o sal. Va acrescentando a farinha.\n3. Sove por 10 minutos e deixe crescer ate dobrar.\n4. Modele em formato de rosca e coloque em forma untada.\n5. Deixe crescer por mais 30 minutos, pincele a gema e polvilhe acucar cristal.\n6. Asse a 180 graus C por 30 minutos."},
    {"nome":"Cuca de Banana","keywords":["cuca"],"categoria":"frio","ingredientes":"Massa:\n2 xicaras de farinha de trigo\n1 xicara de acucar\n2 ovos\n1/2 xicara de leite\n1/2 xicara de oleo\n1 colher (sopa) de fermento\nFarelo:\n1 xicara de farinha de trigo\n1/2 xicara de acucar\n100g de manteiga\n1 colher (cha) de canela\n4 bananas fatiadas","modo":"1. Bata os ovos com o acucar. Adicione o leite e o oleo. Acrescente a farinha e o fermento.\n2. Despeje em forma untada e distribua as bananas fatiadas por cima.\n3. Misture os ingredientes do farelo ate virar uma farofa. Espalhe sobre as bananas.\n4. Asse a 180 graus C por 35 minutos."},
    {"nome":"Bolo de Laranja","keywords":["laranja"],"categoria":"frio","ingredientes":"3 ovos\n1 xicara de acucar\n1/2 xicara de oleo\nSuco e raspas de 2 laranjas\n2 xicaras de farinha de trigo\n1 colher (sopa) de fermento\nCalda: suco de 1 laranja + 4 colheres de acucar","modo":"1. Bata os ovos com o acucar. Adicione o oleo, o suco e as raspas de laranja.\n2. Acrescente a farinha e o fermento. Misture ate homogeneizar.\n3. Despeje em forma untada e asse a 180 graus C por 35 minutos.\n4. Misture o suco com o acucar e despeje sobre o bolo ainda quente."},
    {"nome":"Bolo de Mel de Engenho","keywords":["mel de engenho","bolo de mel"],"categoria":"frio","ingredientes":"3 ovos\n1 xicara de mel de engenho\n1 xicara de acucar\n1/2 xicara de oleo\n2 xicaras de farinha de trigo\n1 colher (cha) de canela\n1 colher (cha) de cravo em po\n1 colher (sopa) de fermento","modo":"1. Bata os ovos com o acucar e o mel.\n2. Adicione o oleo e as especiarias.\n3. Acrescente a farinha e o fermento.\n4. Despeje em forma untada e asse a 180 graus C por 40 minutos."},
    {"nome":"Torta de Frango","keywords":["torta de frango"],"categoria":"frio","ingredientes":"Massa:\n2 xicaras de farinha de trigo\n1 xicara de leite\n1/2 xicara de oleo\n2 ovos\n1 colher (sopa) de fermento\nSal a gosto\nRecheio:\n500g de frango cozido e desfiado\n1 lata de milho\n1 lata de ervilha\n2 tomates picados\nSal e temperos a gosto","modo":"1. Bata todos os ingredientes da massa no liquidificador.\n2. Refogue o frango com os temperos, o milho, a ervilha e os tomates.\n3. Unte uma forma, despeje metade da massa, coloque o recheio e cubra com o restante.\n4. Asse a 180 graus C por 40 minutos ate dourar."},
    {"nome":"Bolo de Pao Amanhecido","keywords":["bolo de pao","pao amanhecido"],"categoria":"frio","ingredientes":"4 paes amanhecidos\n2 xicaras de leite\n3 ovos\n1 xicara de acucar\n2 colheres (sopa) de margarina\n1 colher (sopa) de fermento\n1 colher (cha) de essencia de baunilha","modo":"1. Molhe os paes no leite e deixe descansar por 10 minutos.\n2. Bata no liquidificador os paes molhados com os ovos, o acucar, a margarina e a baunilha.\n3. Adicione o fermento e misture rapidamente.\n4. Despeje em forma untada e asse a 180 graus C por 40 minutos."},
    {"nome":"Quiche de Queijo e Presunto","keywords":["quiche"],"categoria":"frio","ingredientes":"Massa:\n200g de farinha de trigo\n100g de manteiga gelada\n1 ovo\nSal a gosto\nRecheio:\n3 ovos\n200ml de creme de leite\n150g de queijo mussarela ralado\n100g de presunto picado\nSal, pimenta e noz-moscada a gosto","modo":"1. Misture a farinha com a manteiga ate virar uma farofa. Adicione o ovo e o sal. Forme uma bola e deixe descansar 30 minutos na geladeira.\n2. Forre uma forma de quiche com a massa.\n3. Bata os ovos com o creme de leite e os temperos. Adicione o queijo e o presunto.\n4. Despeje sobre a massa e asse a 180 graus C por 35 minutos."},
    {"nome":"Pao Doce Recheado com Doce de Leite","keywords":["pao doce"],"categoria":"frio","ingredientes":"500g de farinha de trigo\n100g de acucar\n1 envelope de fermento biologico\n2 ovos\n100g de manteiga\n150ml de leite morno\n1 colher (cha) de sal\n1 lata de doce de leite para rechear\n1 gema para pincelar","modo":"1. Dissolva o fermento no leite morno com o acucar.\n2. Adicione os ovos, a manteiga e o sal. Va acrescentando a farinha e sove por 10 minutos.\n3. Deixe crescer por 1 hora.\n4. Divida a massa, abra com rolo, coloque doce de leite e feche enrolando.\n5. Coloque em assadeira untada, deixe crescer por 30 minutos e pincele a gema.\n6. Asse a 180 graus C por 25 minutos."},
    {"nome":"Canjica","keywords":["canjica","mugunza"],"categoria":"frio","ingredientes":"500g de canjica branca\n1 lata de leite condensado\n1 litro de leite\n1 vidro de leite de coco\n100g de coco ralado\nCanela e cravo a gosto","modo":"1. Deixe a canjica de molho em agua por 8 horas.\n2. Cozinhe na pressao por 20 minutos.\n3. Adicione o leite, o leite condensado, o leite de coco, o coco ralado e o cravo.\n4. Cozinhe em fogo baixo mexendo ate engrossar levemente.\n5. Sirva com canela polvilhada."},
    {"nome":"Bolo de Amendoim","keywords":["bolo de amendoim"],"categoria":"frio","ingredientes":"2 xicaras de farinha de trigo\n1 e 1/2 xicara de acucar\n3 ovos\n1 xicara de leite\n1/2 xicara de oleo\n1 xicara de amendoim torrado e moido\n1 colher (sopa) de fermento","modo":"1. Bata os ovos com o acucar e o oleo.\n2. Adicione o leite e o amendoim moido.\n3. Acrescente a farinha e o fermento.\n4. Despeje em forma untada e asse a 180 graus C por 35 minutos."},
    {"nome":"Bolo de Tapioca","keywords":["bolo de tapioca","tapioca"],"categoria":"frio","ingredientes":"2 xicaras de tapioca granulada\n1 lata de leite condensado\n1 litro de leite\n1 vidro de leite de coco\n1 xicara de coco ralado\n3 ovos","modo":"1. Deixe a tapioca de molho no leite por 30 minutos.\n2. Bata no liquidificador com os ovos, o leite condensado e o leite de coco.\n3. Adicione o coco ralado e misture.\n4. Despeje em forma untada e asse em banho-maria a 180 graus C por 50 minutos.\n5. Deixe esfriar antes de desenformar."},
    {"nome":"Pao de Queijo Simples","keywords":["pao de queijo"],"categoria":"basico","ingredientes":"1/2 xicara de parmesao ralado\n1/2 xicara de polvilho azedo ou doce\n1/2 caixinha de creme de leite\nSal a gosto","modo":"1. Misture o parmesao e o polvilho.\n2. Va acrescentando o creme de leite aos poucos ate obter uma massa que de para fazer bolinhas.\n3. Faca as bolinhas e coloque em assadeira untada.\n4. Leve ao forno pre-aquecido a 180 graus C ate dourar."},
    {"nome":"Pao de Sal ou Pao de Leite","keywords":["pao de sal","pao de leite"],"categoria":"basico","ingredientes":"2 envelopes de fermento biologico seco (20g)\n1 copo de leite (250ml)\n1/3 xicara de acucar\n1/3 xicara de leite em po\n2 ovos\n2 colheres (sopa) de manteiga\n1/2 colher (sopa) de sal\n600g de farinha de trigo\n1 gema + 2 colheres de leite para pincelar","modo":"1. Misture o fermento, o leite, o acucar, o leite em po, os ovos e o sal.\n2. Va acrescentando a farinha aos poucos e sove por 10 minutos.\n3. Divida em porcoes, boleie e deixe descansar ate dobrar de volume.\n4. Abra cada porcao com rolo e enrole para formar os paes.\n5. Coloque em assadeira untada e deixe descansar por mais 30 minutos.\n6. Pincele com a gema e leve ao forno a 180 graus C por 25 minutos."},
    {"nome":"Pao Caseiro Recheado","keywords":["pao caseiro"],"categoria":"basico","ingredientes":"1 kg de farinha de trigo\n100g de acucar\n20g de sal\n50g de leite em po\n70g de margarina\n2 ovos\n200ml de leite\n15 a 20g de fermento biologico\nAgua gelada para dar o ponto\nRecheio de sua preferencia","modo":"1. Misture todos os ingredientes secos. Adicione os ovos e o leite. De o ponto com agua gelada. Sove ate a massa ficar macia.\n2. Divida em pedacos de 200 a 250g. Abra com rolo e acrescente o recheio.\n3. Enrole como rocambole e disponha em assadeira untada.\n4. Asse em forno medio a 180 graus C por 30 a 40 minutos."},
    {"nome":"Mini Focaccia","keywords":["focaccia"],"categoria":"basico","ingredientes":"1 kg de farinha de trigo\n20g de sal\n200g de acucar\n100g de margarina\n2 ovos\n30g de fermento biologico\n500ml de leite\nAzeite de oliva para untar","modo":"1. Misture o fermento com o acucar ate dissolver. Acrescente o leite, a margarina e os ovos.\n2. Adicione a farinha e o sal aos poucos. Sove bem.\n3. Forme uma bola, cubra e deixe descansar ate dobrar de volume.\n4. Abra a massa em forma untada com azeite. Pressione com as pontas dos dedos.\n5. Regue com azeite e acrescente o recheio desejado. Deixe descansar 20 minutos.\n6. Leve ao forno a 200 graus C por 20 minutos."},
    {"nome":"Enroladinho de Salsicha","keywords":["salsicha","enroladinho"],"categoria":"basico","ingredientes":"250ml de agua morna\n75ml de oleo\n2 colheres (sopa) de acucar\n1/2 colher (sopa) de sal\n1 pacote de fermento biologico seco (10g)\n500g de farinha de trigo\n2 salsichas cortadas em 3 partes cada","modo":"1. Misture todos os ingredientes da massa e sove ate dar ponto.\n2. Faca bolinhas de 10g cada.\n3. Abra cada bolinha, coloque um pedaco de salsicha com molho e enrole.\n4. Disponha em assadeira untada.\n5. Leve ao forno pre-aquecido a 180 graus C ate dourar."},
    {"nome":"Cookies de Chocolate","keywords":["cookie"],"categoria":"basico","ingredientes":"1 kg de pre-mistura para cookie\n200g de farinha de trigo\n300g de margarina\n6 ovos\n200g de gotas de chocolate","modo":"1. Coloque todos os ingredientes na batedeira e bata por 2 minutos.\n2. Acrescente as gotas de chocolate.\n3. Transfira para formas untadas.\n4. Asse por 35 a 40 minutos a 180 graus C."},
    {"nome":"Baguete Recheada","keywords":["baguete"],"categoria":"basico","ingredientes":"500ml de agua temperatura ambiente\n50ml de azeite\n1 colher (sopa) de acucar\n1 colher (sopa) rasa de sal\n2 colheres (sopa) de fermento seco\n800g de farinha de trigo\n300g de presunto\n200g de queijo mussarela","modo":"1. Misture a agua, o azeite, o acucar, o sal e o fermento. Va acrescentando a farinha e sove por 10 minutos.\n2. Deixe descansar por 10 minutos.\n3. Abra a massa bem fina, coloque o recheio e feche as pontas.\n4. Faca cortes em diagonal e pincele a gema.\n5. Deixe descansar de 10 a 15 minutos.\n6. Leve ao forno a 180 graus C por 18 a 20 minutos."},
    {"nome":"Bolinho de Queijo","keywords":["bolinho"],"categoria":"basico","ingredientes":"100g de queijo mussarela ralado grosso\n100g de queijo prato ralado grosso\n1/4 colher (cha) de sal\n1/2 colher (cha) de oregano\n1/8 colher (cha) de pimenta do reino\n1 e 1/2 colher (sopa) de claras\n1/4 xicara de amido de milho","modo":"1. Em uma tigela, acrescente todos os ingredientes e misture bem.\n2. Faca bolinhas pequenas de 10g cada.\n3. Passe no amido de milho.\n4. Frite em oleo quente a 180 graus C."},
    {"nome":"Pao de Aveia com Iogurte","keywords":["aveia"],"categoria":"basico","ingredientes":"4 ovos\n1 pote de iogurte natural (170g)\nSal a gosto\n50g de queijo parmesao ralado\n2 xicaras de farinha de aveia\n1 colher (sobremesa) fermento quimico","modo":"1. No liquidificador coloque todos os ingredientes, menos o fermento.\n2. Acrescente o fermento e misture com espatula.\n3. Despeje em forma de silicone untada e enfarinhada.\n4. Polvilhe queijo parmesao.\n5. Leve ao forno a 180 graus C entre 20 a 25 minutos."},
    {"nome":"Pao de Milho","keywords":["milho"],"categoria":"basico","ingredientes":"75ml de leite\n1/2 lata de milho em conserva (sem agua)\n1 ovo\n1/2 colher (sopa) de essencia de baunilha\n1 e 1/2 colher (sopa) de manteiga\n1/4 colher (sopa) de sal\n1/2 lata de leite condensado\n10g de fermento biologico seco\n500g de farinha de trigo","modo":"1. No liquidificador, bata o leite e o milho.\n2. Acrescente o ovo, a baunilha, a manteiga, o sal, o leite condensado e bata. Por ultimo acrescente o fermento.\n3. Despeje em uma tigela, va acrescentando a farinha e sovando por 10 minutos.\n4. Deixe descansar por 30 minutos.\n5. Divida em 10 partes, boleie e deixe descansar por mais 1 hora.\n6. Pincele uma gema e leve ao forno a 180 graus C por 35 minutos."},
    {"nome":"Pao de Cenoura","keywords":["pao de cenoura"],"categoria":"basico","ingredientes":"1/3 de xicara de oleo\n1 colher (sopa) de manteiga\n2 xicaras de cenoura\n1 ovo\n2 colheres (sopa) de acucar\n7g de fermento biologico seco\n500g de farinha de trigo","modo":"1. Bata todos os ingredientes no liquidificador exceto o fermento e a farinha.\n2. Transfira para um recipiente, acrescente o fermento e misture.\n3. Acrescente a farinha aos poucos ate dar o ponto.\n4. Cubra e deixe descansar por 1 hora.\n5. Modele os paezinhos e leve ao forno a 200 graus C por 20 minutos."},
    {"nome":"Pao de Abacate","keywords":["abacate"],"categoria":"basico","ingredientes":"1 abacate medio maduro (400g de polpa)\n100ml de oleo\n250ml de leite\n2 ovos\n1/2 xicara de acucar\n1 pacote de fermento biologico seco\n1kg de farinha de trigo\n1 colher (cha) de sal","modo":"1. No liquidificador, bata o abacate, o oleo, o leite, os ovos e o acucar. Acrescente o fermento e bata mais um pouco.\n2. Despeje em uma tigela, acrescente o sal e aos poucos a farinha ate a massa comecar a desgrudar da mao.\n3. Sove por 10 minutos.\n4. Deixe descansar por 30 minutos.\n5. Abra a massa, enrole como rocambole e deixe descansar por mais 30 minutos.\n6. Leve ao forno a 180 graus C por 30 minutos."},
    {"nome":"Torta de Escarola","keywords":["escarola","torta"],"categoria":"basico","ingredientes":"Massa:\n500g de farinha de trigo\n1/2 copo de agua\n1/2 copo de oleo\n1 colher (sopa) de vinagre\nSal a gosto\nRecheio:\n1 maco de escarola\n2 dentes de alho\n1 cebola media\nAzeite, sal e temperos a gosto\n2 tomates medios em fatias\n150g de mussarela\nOregano a gosto","modo":"1. Corte a escarola bem fina. Refogue no azeite com a cebola e alho ate soltar agua. Tempere e reserve.\n2. Misture a agua, o oleo e va acrescentando farinha ate dar um ponto.\n3. Divida a massa em duas partes e abra bem fina.\n4. Forre a forma com uma parte. Coloque o recheio, o tomate e oregano.\n5. Finalize com mussarela e feche com a outra parte da massa.\n6. Leve ao forno a 180 graus C por 1 hora ate dourar."},
    {"nome":"Pamonha de Forno","keywords":["pamonha"],"categoria":"basico","ingredientes":"3 latas de milho verde\n4 ovos\n1 vidro de leite de coco (200ml)\n1 lata de leite condensado (395ml)\n1 colher (sopa) de manteiga sem sal\n1 xicara de leite (210ml)\n1 colher (sopa) de fermento quimico","modo":"1. Bata no liquidificador o milho, os ovos e o leite de coco por 3 minutos.\n2. Acrescente o leite condensado, o leite e a manteiga e bata por mais 4 minutos.\n3. Por ultimo acrescente o fermento e bata um pouco.\n4. Despeje em forma untada com manteiga e farinha de milho.\n5. Leve ao forno a 180 graus C por 1 hora."},
    {"nome":"Empadinha de Leite Condensado","keywords":["empadinha"],"categoria":"basico","ingredientes":"1/2 xicara de farinha de trigo (70g)\n3 e 1/2 colher de manteiga em ponto de pomada (38g)\n200ml de leite condensado","modo":"1. Misture a farinha e a manteiga ate formar uma massa lisa.\n2. Abra a massa em forminhas de empadas e leve a geladeira por 20 minutos.\n3. Pre-aqueca o forno a 180 graus C.\n4. Preencha metade de cada forminha com leite condensado.\n5. Leve ao forno a 180 graus C por 20 a 25 minutos ou ate o leite condensado comecar a dourar.\n6. Deixe esfriar para desenformar."},
    {"nome":"Eclair","keywords":["eclair","carolina"],"categoria":"basico","ingredientes":"Massa:\n80g de farinha de trigo\n2 ovos\n70g de manteiga sem sal\n140ml de agua\n3g de acucar\nRecheio (Creme de Baunilha):\n2 ovos\n240ml de leite\n60g de acucar\n20g de amido de milho\n20g de manteiga sem sal\nEssencia de baunilha a gosto\nCobertura (Ganache):\n50g de creme fresco\n50g de chocolate amargo","modo":"1. Em uma panela acrescente a manteiga, acucar, sal e a agua e leve ao fogo ate a manteiga derreter. Desligue, acrescente a farinha mexendo bem. Cozinhe por mais 2 minutos.\n2. Despeje em uma tigela, espalhe e deixe esfriar. Acrescente os ovos batidos aos poucos ate a massa desgrudar da espatula formando um V.\n3. Coloque em saco de confeitar e faca canudinhos de 10cm em forma com papel manteiga.\n4. Leve ao forno a 180 graus C por 25 minutos. Baixe para 160 graus C por mais 15 minutos. Retire e deixe esfriar.\n5. Para o recheio: misture os ovos, o acucar, o amido e o leite numa panela. Leve ao fogo mexendo ate borbulhar. Retire, acrescente a manteiga, cubra com plastico filme e leve a geladeira.\n6. Para o ganache: derreta o chocolate em banho maria e acrescente o creme de leite.\n7. Recheie os eclairs com o creme e cubra com o ganache."},
    {"nome":"Pao Frances","keywords":["pao frances","pao franca"],"categoria":"basico","ingredientes":"1 kg de farinha de trigo\n10g de sal\n10g de acucar\n15g de fermento biologico seco\n600ml de agua gelada\n20g de margarina","modo":"1. Misture a farinha, o sal, o acucar e o fermento.\n2. Adicione a margarina e va acrescentando a agua gelada aos poucos.\n3. Sove por 15 minutos ate ficar uma massa lisa e elastica.\n4. Deixe descansar por 30 minutos.\n5. Divida em porcoes de 50g, boleie e coloque em assadeira.\n6. Deixe crescer por 1 hora e asse a 220 graus C por 15 minutos."},
    {"nome":"Pao de Forma","keywords":["pao de forma","forma"],"categoria":"basico","ingredientes":"500g de farinha de trigo\n10g de sal\n40g de acucar\n10g de fermento biologico seco\n50g de manteiga\n280ml de leite morno\n1 ovo","modo":"1. Misture o fermento com o leite morno e o acucar.\n2. Adicione o ovo, a manteiga e o sal. Va acrescentando a farinha e sove por 10 minutos.\n3. Deixe crescer por 1 hora.\n4. Modele em formato de pao e coloque em forma de bolo ingles untada.\n5. Deixe crescer ate atingir a borda da forma.\n6. Asse a 180 graus C por 30 minutos."},
    {"nome":"Biscoito de Polvilho","keywords":["biscoito de polvilho","polvilho"],"categoria":"basico","ingredientes":"500g de polvilho azedo\n1 colher (cha) de sal\n1/2 xicara de oleo\n1 ovo\nAgua quente o suficiente para dar o ponto","modo":"1. Misture o polvilho com o sal.\n2. Adicione o oleo e o ovo.\n3. Va acrescentando agua quente aos poucos, amassando ate ficar uma massa que de para enrolar.\n4. Faca rolinhos e coloque em assadeira.\n5. Asse a 180 graus C por 25 minutos ate ficarem crocantes."},
    {"nome":"Rosquinha de Nata","keywords":["rosquinha","nata"],"categoria":"basico","ingredientes":"500g de farinha de trigo\n200g de acucar\n200g de nata ou creme de leite fresco\n2 ovos\n1 colher (sopa) de fermento quimico\n1 colher (cha) de essencia de baunilha","modo":"1. Misture todos os ingredientes ate formar uma massa homogenea.\n2. Abra a massa na espessura de 1 cm e corte com cortador de rosquinha.\n3. Frite em oleo quente a 170 graus C ate dourar.\n4. Escorra e passe no acucar ainda quente."},
    {"nome":"Sonho","keywords":["sonho"],"categoria":"basico","ingredientes":"500g de farinha de trigo\n80g de acucar\n10g de fermento biologico seco\n3 ovos\n80g de manteiga\n150ml de leite morno\n1 colher (cha) de sal\nRecheio: creme de confeiteiro ou doce de leite\nAcucar de confeiteiro para polvilhar","modo":"1. Misture o fermento com o leite morno. Adicione os ovos, a manteiga, o sal e o acucar. Va acrescentando a farinha e sove por 10 minutos.\n2. Deixe crescer por 1 hora.\n3. Abra a massa e corte circulos. Deixe crescer por mais 30 minutos.\n4. Frite em oleo a 170 graus C virando uma vez.\n5. Drene, recheie com bico de confeitar e polvilhe acucar de confeiteiro."},
    {"nome":"Coxinha","keywords":["coxinha"],"categoria":"basico","ingredientes":"Massa:\n500g de farinha de trigo\n500ml de caldo de frango\n1 colher (sopa) de manteiga\nSal a gosto\nRecheio:\n500g de frango cozido e desfiado\n1 cebola picada\nSalsinha e sal a gosto\nPara empanar: farinha de rosca e ovo","modo":"1. Leve o caldo ao fogo com a manteiga e o sal. Quando ferver, adicione a farinha de uma vez mexendo ate soltar da panela.\n2. Deixe esfriar e sove a massa.\n3. Refogue a cebola com o frango e tempere.\n4. Abra porcoes de massa na palma da mao, coloque o recheio e modele no formato de coxinha.\n5. Passe no ovo batido e na farinha de rosca.\n6. Frite em oleo quente ate dourar."},
    {"nome":"Pao de Batata Doce","keywords":["batata doce","pao de batata doce"],"categoria":"basico","ingredientes":"300g de batata doce cozida e amassada\n400g de farinha de trigo\n1 envelope de fermento biologico seco\n2 ovos\n50g de manteiga\n1 colher (cha) de sal\n2 colheres (sopa) de acucar\n50ml de leite morno","modo":"1. Misture o fermento com o leite morno e o acucar.\n2. Adicione a batata doce amassada, os ovos, a manteiga e o sal.\n3. Acrescente a farinha aos poucos e sove por 10 minutos.\n4. Deixe crescer por 1 hora.\n5. Modele paezinhos e deixe crescer por mais 30 minutos.\n6. Asse a 180 graus C por 25 minutos."},
    {"nome":"Esfirra Aberta","keywords":["esfirra","esfiha"],"categoria":"basico","ingredientes":"Massa:\n500g de farinha de trigo\n1 envelope de fermento biologico seco\n1 colher (cha) de sal\n1 colher (sopa) de acucar\n200ml de agua morna\n50ml de oleo\nRecheio de carne:\n300g de carne moida\n1 cebola picada\n2 tomates picados\nSuco de 1 limao\nSal e pimenta a gosto","modo":"1. Dissolva o fermento na agua morna com o acucar. Misture com a farinha, o sal e o oleo. Sove e deixe crescer 1 hora.\n2. Misture todos os ingredientes do recheio cru.\n3. Abra a massa em circulos, coloque o recheio e aperte as bordas em 3 pontas.\n4. Deixe descansar 20 minutos e asse a 200 graus C por 20 minutos."},
    {"nome":"Broa de Milho","keywords":["broa","broa de milho"],"categoria":"basico","ingredientes":"2 xicaras de fuba\n1 xicara de farinha de trigo\n1 xicara de acucar\n1 xicara de coco ralado\n2 ovos\n1 xicara de leite\n1/2 xicara de manteiga derretida\n1 colher (sopa) de fermento quimico","modo":"1. Misture todos os ingredientes secos.\n2. Adicione os ovos, o leite e a manteiga derretida. Misture bem.\n3. Modele em bolinhas e coloque em assadeira untada.\n4. Asse a 180 graus C por 20 a 25 minutos ate dourar."},
    {"nome":"Torta Salgada de Liquidificador","keywords":["torta salgada","torta liquidificador"],"categoria":"basico","ingredientes":"Massa:\n2 xicaras de farinha de trigo\n1 xicara de leite\n1/2 xicara de oleo\n3 ovos\n1 colher (sopa) de fermento\nSal a gosto\nRecheio a gosto: atum, palmito, legumes","modo":"1. Bata todos os ingredientes da massa no liquidificador.\n2. Prepare o recheio de sua preferencia temperado a gosto.\n3. Despeje metade da massa em forma untada, adicione o recheio e cubra com o restante.\n4. Asse a 180 graus C por 40 minutos ate dourar."},
    {"nome":"Biscoito Amanteigado","keywords":["biscoito amanteigado","amanteigado"],"categoria":"basico","ingredientes":"200g de manteiga em temperatura ambiente\n100g de acucar de confeiteiro\n1 ovo\n300g de farinha de trigo\n1 colher (cha) de essencia de baunilha","modo":"1. Bata a manteiga com o acucar ate ficar cremosa.\n2. Adicione o ovo e a baunilha.\n3. Acrescente a farinha aos poucos ate formar uma massa.\n4. Modele os biscoitos ou passe na maquina de biscoito.\n5. Asse a 170 graus C por 12 a 15 minutos."},
    {"nome":"Brownie","keywords":["brownie"],"categoria":"basico","ingredientes":"200g de chocolate meio amargo\n150g de manteiga\n3 ovos\n200g de acucar\n100g de farinha de trigo\n1 colher (cha) de baunilha\n1 pitada de sal","modo":"1. Derreta o chocolate com a manteiga em banho-maria. Deixe esfriar.\n2. Bata os ovos com o acucar ate ficar espumoso.\n3. Adicione o chocolate derretido, a baunilha e o sal.\n4. Acrescente a farinha e misture delicadamente.\n5. Despeje em forma untada e asse a 180 graus C por 25 minutos."},
    {"nome":"Palitinho de Queijo","keywords":["palitinho","palito de queijo"],"categoria":"basico","ingredientes":"200g de queijo parmesao ralado\n100g de manteiga\n100g de farinha de trigo\n1 gema\n1 colher (cha) de sal","modo":"1. Misture todos os ingredientes ate formar uma massa homogenea.\n2. Coloque em saco de confeitar com bico estrela.\n3. Faca tiras em assadeira.\n4. Asse a 170 graus C por 15 minutos ate dourar levemente."},
    {"nome":"Pao de Hamburguer","keywords":["hamburguer","pao de hamburguer"],"categoria":"basico","ingredientes":"500g de farinha de trigo\n10g de sal\n50g de acucar\n10g de fermento biologico seco\n50g de manteiga\n1 ovo\n200ml de leite morno\nGergelim para polvilhar","modo":"1. Misture o fermento com o leite morno e o acucar.\n2. Adicione o ovo, a manteiga e o sal. Va acrescentando a farinha e sove por 10 minutos.\n3. Deixe crescer por 1 hora.\n4. Divida em porcoes de 80g e boleie.\n5. Coloque em assadeira, pincele com ovo e polvilhe gergelim.\n6. Deixe crescer por 30 minutos e asse a 180 graus C por 20 minutos."},
    {"nome":"Pastel Frito","keywords":["pastel frito"],"categoria":"basico","ingredientes":"Massa:\n500g de farinha de trigo\n1 colher (cha) de sal\n1 colher (sopa) de vinagre\n1 colher (sopa) de cachaca ou vodka\n200ml de agua morna\n2 colheres (sopa) de oleo\nRecheio: queijo e presunto a gosto","modo":"1. Misture a farinha com o sal. Adicione o vinagre, a cachaca, o oleo e a agua.\n2. Sove ate ficar uma massa lisa. Deixe descansar 30 minutos.\n3. Abra bem fina, corte em retangulos e coloque o recheio.\n4. Feche apertando as bordas com garfo.\n5. Frite em oleo bem quente ate dourar dos dois lados."},
    {"nome":"Creme de Confeiteiro","keywords":["creme de confeiteiro","creme confeiteiro"],"categoria":"basico","ingredientes":"500ml de leite\n4 gemas\n100g de acucar\n40g de amido de milho\n1 colher (sopa) de manteiga\n1 colher (cha) de essencia de baunilha","modo":"1. Misture as gemas com o acucar e o amido ate ficar homogeneo.\n2. Aqueca o leite ate quase ferver e despeje sobre a mistura de gemas aos poucos mexendo sempre.\n3. Volte ao fogo baixo, mexendo sem parar ate engrossar.\n4. Retire do fogo, adicione a manteiga e a baunilha.\n5. Cubra com plastico filme rente ao creme e deixe esfriar na geladeira."},
    {"nome":"Banana Caramelizada","keywords":["banana caramelizada"],"categoria":"basico","ingredientes":"4 bananas\n4 colheres (sopa) de acucar\n2 colheres (sopa) de manteiga\n1 colher (cha) de canela","modo":"1. Derreta a manteiga em frigideira.\n2. Adicione o acucar e deixe caramelizar.\n3. Coloque as bananas cortadas ao meio e cozinhe por 2 minutos de cada lado.\n4. Polvilhe canela e sirva quente sobre sorvete ou acompanhando paes."},
    {"nome":"Pao Integral","keywords":["pao integral","integral"],"categoria":"basico","ingredientes":"300g de farinha de trigo integral\n200g de farinha de trigo branca\n1 envelope de fermento biologico seco\n1 colher (cha) de sal\n1 colher (sopa) de mel\n2 colheres (sopa) de azeite\n300ml de agua morna","modo":"1. Misture as farinhas, o fermento e o sal.\n2. Adicione o mel, o azeite e a agua morna aos poucos.\n3. Sove por 10 minutos ate ficar uma massa elastica.\n4. Deixe crescer por 1 hora coberto com pano umido.\n5. Modele em forma de pao e coloque em forma untada.\n6. Deixe crescer por mais 30 minutos e asse a 200 graus C por 30 minutos."},
    {"nome":"Churros","keywords":["churros"],"categoria":"basico","ingredientes":"250ml de agua\n250g de farinha de trigo\n1 colher (cha) de sal\n1 colher (sopa) de acucar\n2 colheres (sopa) de oleo\nOleo para fritar\nAcucar e canela para passar\nRecheio: doce de leite ou chocolate","modo":"1. Ferva a agua com o sal, o acucar e o oleo.\n2. Retire do fogo e adicione a farinha de uma vez mexendo ate soltar da panela.\n3. Coloque em saco de confeitar com bico estrela.\n4. Frite em oleo a 180 graus C ate dourar.\n5. Passe no acucar com canela.\n6. Recheie com doce de leite usando saco de confeitar."},
    {"nome":"Pao de Queijo de Liquidificador","keywords":["pao de queijo liquidificador"],"categoria":"basico","ingredientes":"1 xicara de leite\n1/2 xicara de oleo\n1 ovo\n2 xicaras de polvilho azedo\n1 xicara de queijo parmesao ralado\n1 colher (cha) de sal","modo":"1. Bata no liquidificador o leite, o oleo e o ovo.\n2. Adicione o polvilho, o queijo e o sal. Bata ate ficar homogeneo.\n3. Despeje em forminhas untadas ou em forma de silicone.\n4. Asse a 180 graus C por 25 a 30 minutos ate dourar."},
    {"nome":"Biscoito de Amendoim","keywords":["biscoito de amendoim"],"categoria":"basico","ingredientes":"1 xicara de amendoim torrado e moido\n1 xicara de farinha de trigo\n1 xicara de acucar\n1 ovo\n2 colheres (sopa) de manteiga\n1 colher (cha) de baunilha","modo":"1. Misture todos os ingredientes ate formar uma massa.\n2. Faca bolinhas e coloque em assadeira untada.\n3. Achate com o garfo fazendo o padrao cruzado.\n4. Asse a 170 graus C por 12 a 15 minutos."},
    {"nome":"Tapioca Recheada","keywords":["tapioca recheada"],"categoria":"basico","ingredientes":"4 colheres (sopa) de goma de tapioca hidratada por porcao\nRecheio a gosto: queijo, banana com mel, frango desfiado, carne seca","modo":"1. Aqueca uma frigideira antiaderente em fogo medio.\n2. Espalhe a goma de tapioca em uma camada uniforme.\n3. Quando as bordas comecarem a soltar e a superficie estiver seca, adicione o recheio de sua preferencia.\n4. Dobre ao meio e sirva imediatamente."},
    {"nome":"Pudim de Leite Condensado","keywords":["pudim de leite"],"categoria":"basico","ingredientes":"1 lata de leite condensado\n2 latas de leite (usar a lata como medida)\n3 ovos\n1 xicara de acucar para a calda","modo":"1. Caramelize o acucar em uma forma de pudim e espalhe pelas laterais.\n2. Bata no liquidificador o leite condensado, o leite e os ovos por 2 minutos.\n3. Despeje na forma caramelizada.\n4. Asse em banho-maria no forno a 180 graus C por 1 hora.\n5. Deixe esfriar completamente antes de desenformar."},
    {"nome":"Bolo de Iogurte","keywords":["bolo de iogurte","iogurte"],"categoria":"basico","ingredientes":"1 pote de iogurte natural (175g)\n2 potes de acucar (usando o pote de iogurte como medida)\n3 potes de farinha de trigo\n1/2 pote de oleo\n3 ovos\n1 colher (sopa) de fermento\nRaspas de 1 limao","modo":"1. Bata o iogurte, o acucar, o oleo e os ovos.\n2. Acrescente a farinha e o fermento. Misture ate homogeneizar.\n3. Adicione as raspas de limao.\n4. Despeje em forma untada e asse a 180 graus C por 35 minutos."},
    {"nome":"Torta de Maca","keywords":["torta de maca"],"categoria":"basico","ingredientes":"Massa:\n300g de farinha de trigo\n150g de manteiga gelada\n2 colheres (sopa) de acucar\n1 pitada de sal\n4 colheres (sopa) de agua gelada\nRecheio:\n5 macas descascadas e fatiadas\n100g de acucar\n1 colher (cha) de canela\n1 colher (sopa) de amido de milho\nSuco de 1 limao","modo":"1. Misture a farinha com a manteiga gelada ate virar uma farofa. Adicione o acucar, o sal e a agua gelada. Forme dois discos e leve a geladeira por 30 minutos.\n2. Misture as macas com o acucar, a canela, o amido e o suco de limao.\n3. Forre a forma com um disco de massa, coloque o recheio e cubra com o outro disco. Faca furos na tampa.\n4. Asse a 200 graus C por 40 a 50 minutos."},
    {"nome":"Pao Sirio","keywords":["pao sirio","pao arabe"],"categoria":"basico","ingredientes":"500g de farinha de trigo\n1 envelope de fermento biologico seco\n1 colher (cha) de sal\n1 colher (cha) de acucar\n300ml de agua morna\n2 colheres (sopa) de azeite","modo":"1. Misture o fermento com a agua morna e o acucar.\n2. Adicione a farinha, o sal e o azeite. Sove por 8 minutos.\n3. Deixe crescer por 1 hora.\n4. Divida em 8 porcoes e abra bem finos com rolo.\n5. Deixe descansar 15 minutos.\n6. Asse em forno muito quente (250 graus C) por 3 a 5 minutos ate inflar e dourar."},
]

for r in RECEITAS:
    cur.execute("""
        INSERT INTO receitas (nome, keywords, categoria, ingredientes, modo)
        VALUES (%s, %s, %s, %s, %s)
    """, (r["nome"], r["keywords"], r["categoria"], r["ingredientes"], r["modo"]))

conn.commit()
cur.execute("SELECT COUNT(*) FROM receitas;")
print(f"Receitas inseridas: {cur.fetchone()[0]}")
cur.close()
conn.close()
print("Pronto!")